spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gadgetariumProject
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 7373
  error:
    include-message: always


app:
  jwt:
    secret: java10